export const SPINE_PROPERTIES_ACTIONS = Object.freeze({
    UPDATE_SPINE_PROPERTIES: "UPDATE_SPINE_PROPERTIES",
    INIT_SPINE_PROPERTIES: "INIT_SPINE_PROPERTIES",
    REMOVE_SPINE_PROPERTIES: "REMOVE_SPINE_PROPERTIES",
    IMPORT_SPINE_PROPERTIES: "IMPORT_SPINE_PROPERTIES",
});
